# Generated by Django 2.2.6 on 2019-11-02 10:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20191031_2251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdetails',
            name='CreateDate',
            field=models.DateField(default=datetime.date.today, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='productdetails',
            name='PriceDescription',
            field=models.CharField(max_length=50, verbose_name='Price Description'),
        ),
    ]
