# Generated by Django 2.2.6 on 2019-11-04 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_auto_20191102_1552'),
    ]

    operations = [
        migrations.CreateModel(
            name='Org_History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tittle', models.CharField(max_length=100, verbose_name='Tittle')),
                ('Sub_Tittle', models.CharField(max_length=100, verbose_name='Sub Tittle')),
                ('Description', models.TextField(max_length=500, verbose_name='Description')),
                ('Image', models.FilePathField(verbose_name='Image')),
            ],
        ),
        migrations.AlterField(
            model_name='productdetails',
            name='Description',
            field=models.TextField(max_length=500, verbose_name='Description'),
        ),
    ]
